### PR TITLE
Create mendoza.yml

### PR DESCRIPTION
**Pull request by nanocastro**

### CODE REVIEW

**Comment by ricki-z** [comment]
Why was that closed?

**Comment by nanocastro** [comment]
sorry, I closed because I'm going to reconnect my sensors in a few hours and I did not want to show the lab info with no sensors... but I wold certainly like to add my lab to the map
The sensors I'm going to reconnect are
esp8266-16614917
esp8266-3912589
esp8266-413996
esp8266-7233236
thanks
saludos

**Comment by ricki-z** [comment]
Thanks for the reply. I will wait with merging until you are ready. Just comment here.

**Comment by nanocastro** [comment]
all set, the 4 sensor are running

**Pull request merged**
